name: Testing Secret sync

on:
  push: {}
  release:
    types: [published]
env:
  ENCODED_PIPELINE_SECRET: ${{ secrets.VAULT_KV_2B3F524E_MY_SECRET }}

jobs:
  secrets:
    name: Accessing JSON secret
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Envs Before
        run: echo "Env values before"

      - name: Decode Secrets
        run: |
          if [ ! -x "$(command -v jq)" ]; then
            echo "jq not found, installing..."
            sudo apt-get update
            sudo apt-get install -y jq
          fi
          echo ${{ secrets.VAULT_KV_2B3F524E_MY_SECRET }} | sed 's/./& /g' |tr -d ' '| jq -r 'to_entries[] | "\(.key)=\(.value)"' 
          echo "${{ env.ENCODED_PIPELINE_SECRET }}" | base64 --decode | jq -r 'to_entries[] | "\(.key)=\(.value)"' 
          echo "where am i?"
          echo "${{ env.ENCODED_PIPELINE_SECRET }}" | jq -r 'to_entries[] | "\(.key)=\(.value)"' | while read line; do echo "$line" >> $GITHUB_ENV; echo "::add-mask::${line#*=}"; done
                
      - name: Envs After
        run: echo "Env values after"
