# Sample GitHub workflow for signing a PowerShell script using a short-lived
# code signing certificate from HashiCorp Vault. This is NOT optimized for a
# production environment.

name: sign-script
run-name: "Sign PowerShell script"

on:
  push: {} # FIXME: For testing purposes only
  release:
    types: [published]

env:
  # Be sure to configure VAULT_ADDR and VAULT_NAMESPACE in your repository variables
  VAULT_ADDR: ${{ vars.VAULT_ADDR }}
  VAULT_NAMESPACE: ${{ vars.VAULT_NAMESPACE }}
  environment: prod

jobs:
  authenticode:
    runs-on: windows-latest
    environment: prod
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Vault CLI
        shell: powershell
        run: |
          Invoke-WebRequest -OutFile "vault.zip" -Uri "https://releases.hashicorp.com/vault/1.16.1/vault_1.16.1_windows_amd64.zip"
          Expand-Archive -Path "vault.zip" -DestinationPath .
          Remove-Item "vault.zip"

      - name: Authenticate to Vault
        uses: hashicorp/vault-action@v3.0.0
        with:
          url: ${{ env.VAULT_ADDR }}
          namespace: ${{ env.VAULT_NAMESPACE }}
          method: jwt
          path: gh-actions
          role: repository
          jwtGithubAudience: ${{ env.VAULT_ADDR }}
          exportToken: true
          
      #- name: Output Synced github secret from HCP Vault
      #  run: |
      #    $secretValue = $env:GITHUB_SECRET_NAME
      #    $spacedSecret = $secretValue -replace '(.)', '$1 ' 
      #    $spacedSecret.TrimEnd() 
      #    Write-Host "The secret is: $spacedSecret"
      #    $spacedSecret | Out-File -FilePath ".\file.txt"
      #    cat ".\file.txt"
      #  shell: pwsh
      #  env:
      #    GITHUB_SECRET_NAME: ${{ secrets.VAULT_KV_2B3F524E_MY_SECRET.foo }}
          
      - name: Get code signing certificate
        shell: pwsh
        run: |
          $Endpoint = "pki-codesign/issue/github-actions"
          $CertSubject = "spiffe://github.com/${{ github.repository }}@${{ github.run_id }}-${{ github.job }}"
          $Cert = $(./vault.exe write -format=json "$Endpoint" common_name="$CertSubject" uri_sans="$CertSubject")
          $CertJson = $Cert | ConvertFrom-Json
          echo $CertJson.data.issuing_ca
          Set-Content -Path "codesigning.crt" -Value "$($CertJson.data.certificate)`n$($CertJson.data.issuing_ca -Join "`n")`n$($CertJson.data.ca_chain -Join "`n")"
          Set-Content -Path "issuing_ca.pem" -Value "$($CertJson.data.issuing_ca)"
          # Get the current directory and store it in a variable
          $currentDirectory = Get-Location

          # Display the current directory
          Write-Host "Current directory: $currentDirectory"
        
          # If you need the path as a string, you can access the Path property
          $currentDirectoryPath = $currentDirectory.Path
          Write-Host "Current directory path: $currentDirectoryPath"
          Set-Content -Path "codesigning.key" -Value "$($CertJson.data.private_key)"
          openssl pkcs12 -export -out ".\codesigning.pfx" -inkey codesigning.key -in codesigning.crt -passout pass:""
          Get-PfxCertificate -FilePath ".\codesigning.pfx"
          Remove-Item -Path codesigning.crt,codesigning.key
      
      #- name: Get code signing CA Chain
      #  shell: powershell
      #  run: |
      #    $certUrl = "${{ env.VAULT_ADDR }}/v1/admin/pki-codesign/ca_chain"
      #    $outputFilePath = "C:\Temp\ca_chain.pem"
      #    
          # Download the CA chain using Invoke-WebRequest
      #    try {
      #        Invoke-WebRequest -Uri $certUrl -OutFile $outputFilePath
      #        Write-Host "CA chain downloaded successfully and saved to $outputFilePath"
      #    } catch {
      #        Write-Host "Error downloading the CA chain: $_"
      #    }
      - name: Import downloaded Issuing CA Chain
        shell: pwsh
        run: |
          $dirPath=$(pwd)
          $dirPath
          openssl x509 -in "$dirPath\issuing_ca.pem" -text
          Set-Location -Path Cert:\LocalMachine\Root
          #lets check whether the cert is correct
          cat $dirPath\issuing_ca.pem
          Import-Certificate -Filepath "$dirPath\issuing_ca.pem"
          
      - name: Sign PowerShell script
        shell: pwsh
        run: |
          #$Cert = Get-PfxCertificate -FilePath ".\codesigning.pfx"
          Write-Host "Let's see what has been imported into the trusted store"
          Get-ChildItem -Path Cert:\LocalMachine\Root -CodeSigningCert
          Write-Host "let's see what's in the pfx file"
          Get-ChildItem -Path ".\codesigning.pfx" | Import-PfxCertificate -CertStoreLocation Cert:\LocalMachine\Root -Exportable
          Write-Host "Importing issuing CA"
          Import-Certificate -CertStoreLocation Cert:\LocalMachine\Root -Filepath ".\issuing_ca.pem"
          
          Write-Host "To check whether the import was done correctly"
          #certutil -store Root
          
          Write-Host "Checking whether we have codesigningcert"
          Get-ChildItem -Path Cert:\LocalMachine\Root -CodeSigningCert
          #$Cert=Get-ChildItem -Path Cert:\LocalMachine\Root -CodeSigningCert
          #Get-PfxCertificate -FilePath ".\codesigning.pfx" -CodeSigningCert
          $Cert=Get-PfxCertificate -FilePath ".\codesigning.pfx" 
          Set-PSDebug -Trace 2; Set-AuthenticodeSignature `
            -Certificate $Cert `
            -FilePath ".\hello-world.ps1" `
            -TimestampServer "http://timestamp.sectigo.com"

      - name: validate signed code
        shell: pwsh
        run: |
          Get-AuthenticodeSignature -FilePath ".\hello-world.ps1"

      - name: Upload signed PowerShell script
        uses: actions/upload-artifact@v3
        with:
          name: signed-powershell
          path: hello-world.ps1
          retention-days: 1
